#!/usr/bin/env bash
#
# VeilPass Development Setup Script
# ===================================
# This script installs dependencies, generates development keys,
# and prepares the local environment for development.
#
# Usage:  chmod +x scripts/setup.sh && ./scripts/setup.sh
#
set -euo pipefail

# ── Colors ─────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Prerequisites Check ───────────────────────────────────────────────────────

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

log_info "Setting up VeilPass development environment..."
log_info "Project directory: $PROJECT_DIR"

check_command() {
    if ! command -v "$1" &>/dev/null; then
        log_error "$1 is not installed. Please install it first."
        case "$1" in
            rustc) echo "  Visit: https://rustup.rs/" ;;
            node)  echo "  Visit: https://nodejs.org/ (v22+)" ;;
            python3) echo "  Visit: https://www.python.org/downloads/ (v3.12+)" ;;
            docker) echo "  Visit: https://docs.docker.com/get-docker/" ;;
            pnpm)  echo "  Install: npm install -g pnpm" ;;
        esac
        return 1
    fi
    log_ok "$1 found: $($1 --version 2>&1 | head -n 1)"
}

check_command rustc  || exit 1
check_command cargo  || exit 1
check_command node   || exit 1
check_command python3 || exit 1

# Optional tools
check_command docker 2>/dev/null || log_warn "Docker not found (optional for API/DB services)"

# ── 1. Rust Setup ─────────────────────────────────────────────────────────────

log_info "Configuring Rust toolchain..."
rustup toolchain install stable 2>/dev/null || true
rustup target add wasm32-unknown-unknown 2>/dev/null || true
log_ok "Rust toolchain ready"

# ── 2. Rust Build & Test ──────────────────────────────────────────────────────

log_info "Building Rust workspace..."
cargo build --workspace 2>&1 | tail -1

log_info "Running Rust tests..."
cargo test --workspace --all-features 2>&1 | tail -3
log_ok "Rust tests passed"

# ── 3. npm CLI Setup ──────────────────────────────────────────────────────────

log_info "Setting up npm CLI..."
cd "$PROJECT_DIR/cli"
npm install 2>&1 | tail -1
npm run build 2>&1 | tail -1
cd "$PROJECT_DIR"
log_ok "npm CLI ready"

# ── 4. Web Frontend Setup ─────────────────────────────────────────────────────

log_info "Setting up web frontend..."
cd "$PROJECT_DIR/apps/web"
npm install 2>&1 | tail -1
cd "$PROJECT_DIR"
log_ok "Web frontend dependencies installed"

# ── 5. Python API Setup ───────────────────────────────────────────────────────

log_info "Setting up Python API..."
cd "$PROJECT_DIR/apps/api"
python3 -m venv .venv 2>/dev/null || python -m venv .venv
# shellcheck disable=SC1091
source .venv/bin/activate
pip install --quiet --upgrade pip 2>&1 | tail -1
pip install --quiet -r requirements.txt 2>&1 | tail -1
deactivate
cd "$PROJECT_DIR"
log_ok "Python API ready"

# ── 6. Generate Development Keys ──────────────────────────────────────────────

log_info "Generating development keys..."
SIGNING_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import os; print(os.urandom(32).hex())")
VERIFICATION_KEY=$(echo -n "$SIGNING_KEY" | python3 -c "
import sys, hashlib
seed = bytes.fromhex(sys.stdin.read().strip())
# Note: This is a placeholder. In production, derive from Ed25519.
print(hashlib.sha256(seed).hexdigest()[:64])
" 2>/dev/null || echo "placeholder-dev-key")

# Create .env file if not exists
if [ ! -f .env ]; then
    cat > .env << EOF
# VeilPass Development Environment
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VEILPASS_SIGNING_KEY=${SIGNING_KEY}
VEILPASS_VERIFICATION_KEY=${VERIFICATION_KEY}
VEILPASS_DATABASE_URL=postgresql+asyncpg://veilpass:veilpass@localhost:5432/veilpass
VEILPASS_REDIS_URL=redis://localhost:6379/0
VEILPASS_RATE_LIMIT=100
NEXT_PUBLIC_API_URL=http://localhost:8000
EOF
    log_ok "Created .env file with development keys"
else
    log_warn ".env file already exists, skipping key generation"
fi

# ── 7. Git Hooks (Optional) ──────────────────────────────────────────────────

if [ -d .git ] && [ ! -f .git/hooks/pre-commit ]; then
    cat > .git/hooks/pre-commit << 'EOF'
#!/bin/sh
# VeilPass pre-commit hook
# Runs formatting and lint checks on staged files.
echo "Running pre-commit checks..."
cargo fmt --all --check || { echo "Format check failed. Run: cargo fmt"; exit 1; }
EOF
    chmod +x .git/hooks/pre-commit
    log_ok "Git pre-commit hook installed"
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "══════════════════════════════════════════════════════════"
echo -e "  ${GREEN}VeilPass development environment is ready!${NC}"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "  Quick commands:"
echo "    cargo build -p veilpass-cli    Build Rust CLI"
echo "    cargo test --workspace         Run all Rust tests"
echo "    cd cli && npm run dev          Run npm CLI in dev mode"
echo "    cd apps/api && uvicorn app.main:app --reload  Start API"
echo "    cd apps/web && npm run dev     Start web frontend"
echo ""
echo "  Start developing:"
echo "    code $PROJECT_DIR"
echo ""
