<#
.SYNOPSIS
    VeilPass Development Setup Script (PowerShell)
.DESCRIPTION
    Installs dependencies, generates development keys, and prepares
    the local environment for VeilPass development on Windows.
.NOTES
    Run from PowerShell 5.1+ or PowerShell 7+:
        .\scripts\setup.ps1
#>

$ErrorActionPreference = "Stop"
$ProjectDir = Split-Path -Parent (Split-Path -Parent $PSCommandPath)

Write-Host "Setting up VeilPass development environment..." -ForegroundColor Cyan
Write-Host "Project directory: $ProjectDir" -ForegroundColor Gray

# ── Helper Functions ───────────────────────────────────────────────────────────

function Test-Command($command) {
    try {
        Get-Command $command -ErrorAction Stop | Out-Null
        Write-Host "[OK] $command found: $(& $command --version 2>&1 | Select-Object -First 1)" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "[ERROR] $command is not installed." -ForegroundColor Red
        switch ($command) {
            "cargo" { Write-Host "  Visit: https://rustup.rs/" }
            "node"  { Write-Host "  Visit: https://nodejs.org/ (v22+)" }
            "python" { Write-Host "  Visit: https://www.python.org/downloads/ (v3.12+)" }
            "docker" { Write-Host "  Optional: https://docs.docker.com/get-docker/" }
        }
        return $false
    }
}

# ── Prerequisites Check ───────────────────────────────────────────────────────

$rustOk = Test-Command "cargo"
$nodeOk = Test-Command "node"
$pyOk = Test-Command "python"
$null = Test-Command "docker"  # optional

if (-not ($rustOk -and $nodeOk -and $pyOk)) {
    Write-Host "[ERROR] Missing required tools. Please install them and try again." -ForegroundColor Red
    exit 1
}

Set-Location $ProjectDir

# ── 1. Rust Setup ─────────────────────────────────────────────────────────────

Write-Host "`nConfiguring Rust toolchain..." -ForegroundColor Cyan
cargo build --workspace 2>&1 | Select-Object -Last 1
Write-Host "[OK] Rust workspace builds" -ForegroundColor Green

Write-Host "Running Rust tests..." -ForegroundColor Cyan
cargo test --workspace --all-features 2>&1 | Select-Object -Last 3
Write-Host "[OK] Rust tests passed" -ForegroundColor Green

# ── 2. npm CLI Setup ──────────────────────────────────────────────────────────

Write-Host "`nSetting up npm CLI..." -ForegroundColor Cyan
Set-Location "$ProjectDir/cli"
npm install 2>&1 | Select-Object -Last 1
npm run build 2>&1 | Select-Object -Last 1
Set-Location $ProjectDir
Write-Host "[OK] npm CLI ready" -ForegroundColor Green

# ── 3. Web Frontend Setup ─────────────────────────────────────────────────────

Write-Host "Setting up web frontend..." -ForegroundColor Cyan
Set-Location "$ProjectDir/apps/web"
npm install 2>&1 | Select-Object -Last 1
Set-Location $ProjectDir
Write-Host "[OK] Web frontend dependencies installed" -ForegroundColor Green

# ── 4. Python API Setup ───────────────────────────────────────────────────────

Write-Host "`nSetting up Python API..." -ForegroundColor Cyan
Set-Location "$ProjectDir/apps/api"
# Check if venv exists, if not create it
if (-not (Test-Path ".venv")) {
    python -m venv .venv
}
# Activate venv and install deps
& "$ProjectDir/apps/api/.venv/Scripts/pip.exe" install --quiet --upgrade pip 2>&1 | Select-Object -Last 1
& "$ProjectDir/apps/api/.venv/Scripts/pip.exe" install --quiet -r requirements.txt 2>&1 | Select-Object -Last 1
Set-Location $ProjectDir
Write-Host "[OK] Python API ready" -ForegroundColor Green

# ── 5. Generate Development Keys ──────────────────────────────────────────────

Write-Host "`nGenerating development keys..." -ForegroundColor Cyan

# Generate a random 32-byte hex key
$randomBytes = New-Object byte[] 32
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$rng.GetBytes($randomBytes)
$signingKey = [System.BitConverter]::ToString($randomBytes) -replace '-', ''

# Derive a verification key placeholder via SHA-256
$sha256 = [System.Security.Cryptography.SHA256]::Create()
$verificationKey = [System.BitConverter]::ToString($sha256.ComputeHash($randomBytes)) -replace '-', ''

# Create .env file if not exists
if (-not (Test-Path ".env")) {
    $envContent = @"
# VeilPass Development Environment
# Generated by setup.ps1 on $(Get-Date -Format 'o')
VEILPASS_SIGNING_KEY=$signingKey
VEILPASS_VERIFICATION_KEY=$verificationKey
VEILPASS_DATABASE_URL=postgresql+asyncpg://veilpass:veilpass@localhost:5432/veilpass
VEILPASS_REDIS_URL=redis://localhost:6379/0
VEILPASS_RATE_LIMIT=100
NEXT_PUBLIC_API_URL=http://localhost:8000
"@
    Set-Content -Path ".env" -Value $envContent -Encoding UTF8
    Write-Host "[OK] Created .env file with development keys" -ForegroundColor Green
} else {
    Write-Host "[WARN] .env file already exists, skipping key generation" -ForegroundColor Yellow
}

# ── 6. Git Hooks (Optional) ──────────────────────────────────────────────────

$hooksDir = ".git/hooks"
if (Test-Path ".git") {
    $preCommitPath = Join-Path $hooksDir "pre-commit"
    if (-not (Test-Path $preCommitPath)) {
        $hookContent = @'
#!/usr/bin/env sh
# VeilPass pre-commit hook
echo "Running pre-commit checks..."
cargo fmt --all --check || { echo "Format check failed. Run: cargo fmt"; exit 1; }
'@
        Set-Content -Path $preCommitPath -Value $hookContent -Encoding UTF8
        Write-Host "[OK] Git pre-commit hook installed" -ForegroundColor Green
    }
}

# ── Summary ───────────────────────────────────────────────────────────────────

Write-Host "`n══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  VeilPass development environment is ready!" -ForegroundColor Green
Write-Host "══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host @"

Quick commands:
  cargo build -p veilpass-cli             Build Rust CLI
  cargo test --workspace                  Run all Rust tests
  cd cli && npm run dev                   Run npm CLI in dev mode
  cd apps/api && .venv\Scripts\uvicorn app.main:app --reload  Start API
  cd apps/web && npm run dev              Start web frontend

Start developing:
  code $ProjectDir
"@
